# Generated by Django 3.1.5 on 2021-01-12 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellidos')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=500, verbose_name='telefono')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('contraseña', models.CharField(max_length=100, verbose_name='contraseña')),
                ('sexo', models.CharField(max_length=2, verbose_name='sexo')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('especie', models.IntegerField(max_length=100, verbose_name='especie')),
                ('raza', models.CharField(max_length=100, verbose_name='raza')),
                ('sexo', models.CharField(max_length=2, verbose_name='sexo')),
                ('fechaN', models.CharField(max_length=50, verbose_name='fechaN')),
                ('color', models.CharField(max_length=100, verbose_name='color')),
                ('observaciones', models.CharField(max_length=250, verbose_name='observaciones')),
                ('carnet', models.CharField(max_length=100, verbose_name='carnet')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.usuario')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10, verbose_name='fecha')),
                ('hora', models.CharField(max_length=60, verbose_name='hora')),
                ('motivo', models.CharField(max_length=100, verbose_name='motivo')),
                ('diagnostico', models.CharField(max_length=100, verbose_name='diagnostico')),
                ('Tratamiento', models.CharField(max_length=100, verbose_name='Tratamiento')),
                ('temperatura', models.CharField(max_length=100, verbose_name='temperatura')),
                ('peso', models.CharField(max_length=100, verbose_name='peso')),
                ('pulso', models.CharField(max_length=100, verbose_name='pulso')),
                ('respiracion', models.CharField(max_length=100, verbose_name='Tratamiento')),
                ('observaciones', models.CharField(max_length=100, verbose_name='observaciones')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
            ],
            options={
                'verbose_name': 'historia',
                'verbose_name_plural': 'historias',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='controlv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaA', models.CharField(max_length=100, verbose_name='fechaA')),
                ('observacion', models.CharField(max_length=250, verbose_name='observaciones')),
                ('notificar', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
                ('tipoV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.tipov')),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10, verbose_name='fecha')),
                ('hora', models.CharField(max_length=60, verbose_name='hora')),
                ('hfin', models.CharField(max_length=60, verbose_name='hora')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
            ],
        ),
    ]
