# Generated by Django 3.1.5 on 2021-01-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurant', verbose_name='Imagen'),
        ),
    ]
